### ISSUE TITLE
lang++ exited with code 1

### ISSUE THREAD

**Issue by LeoJHarris** [AdamEssenmacher/GoogleApisForiOSComponents#73]
**Before reporting a bug:**
- [x ] I have read the project readme and followed all instructions.
- [x ] I have searched this project for potentially duplicate issues (even closed ones).

**Describe the bug**
Hitting the following exception when trying to build on the latest NuGet 11.6.0 where its throwing the following build error, rolling back to 11.3.0 works fine.

clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_FIRConsentStatusDenied", referenced from:
      <initial-undefines>
  "_FIRConsentStatusGranted", referenced from:
      <initial-undefines>
  "_FIRConsentTypeAdPersonalization", referenced from:
      <initial-undefines>
  "_FIRConsentTypeAdStorage", referenced from:
      <initial-undefines>
  "_FIRConsentTypeAdUserData", referenced from:
      <initial-undefines>
  "_FIRConsentTypeAnalyticsStorage", referenced from:
      <initial-undefines>
  "_OBJC_CLASS_$_FIRAnalytics", referenced from:
       in registrar.o
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Environment (please complete the following information):**
- OS: iOS 18.1
- IDE (if applicable): NA
- .NET version .NET 9.0

**.csproj**
If you're experiencing a build issue, please include a redacted copy of your .csproj file.

**Additional context**
Unable to build application with latest v11.6.0

**Comment by AdamEssenmacher** [comment]
Can you share your csproj?

**Comment by LeoJHarris** [comment]
> Can you share your csproj?

@AdamEssenmacher 

```csproj

<PropertyGroup>
	<TargetFrameworks>net9.0-ios;net9.0-android</TargetFrameworks>
	<!-- xUnit: Add net8.0; here -->
	<OutputType Condition="'$(TargetFramework)' != 'net9.0'">Exe</OutputType>
	<SingleProject>true</SingleProject>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<UseMaui>true</UseMaui>

	<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
	<WindowsPackageType>None</WindowsPackageType>

	<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
	<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
	<OutputPath>bin\$(Configuration)\</OutputPath>

	<FirebaseCrashlyticsUploadSymbolsEnabled>true</FirebaseCrashlyticsUploadSymbolsEnabled>
	<FirebaseCrashlyticsUploadSymbolsContinueOnError>false</FirebaseCrashlyticsUploadSymbolsContinueOnError>
</PropertyGroup>

<Choose>
	<When Condition="$(DefineConstants.Contains('DEBUG'))">
		<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
			<DebugSymbols>true</DebugSymbols>
			<MtouchUseLlvm>false</MtouchUseLlvm>
			<UseInterpreter>true</UseInterpreter>
			<MtouchInterpreter>all</MtouchInterpreter>
			<EnableSGenConc>false</EnableSGenConc>
			<MtouchDebug>true</MtouchDebug>
			<OptimizePNGs>false</OptimizePNGs>
			<MtouchNoSymbolStrip>true</MtouchNoSymbolStrip>
			<AdditionalArgs>-v -v -v -v</AdditionalArgs>
			<AotAssemblies>true</AotAssemblies>
			<MtouchLink>None</MtouchLink>
		</PropertyGroup>
	</When>
	<Otherwise>
	</Otherwise>
</Choose>

<ItemGroup>
	<PackageReference Include="AdamE.Firebase.iOS.Analytics" Version="11.3.0" />
	<PackageReference Include="AdamE.Firebase.iOS.Core" Version="11.3.0" />
	<PackageReference Include="AdamE.Firebase.iOS.Crashlytics" Version="11.3.0" />
	<PackageReference Include="AdamE.Firebase.iOS.Installations" Version="11.3.0" />
	<PackageReference Include="CommunityToolkit.Maui.Camera" Version="2.0.0" />
	<PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.0.0" />
	<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.1" />
	<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.1" />
	<PackageReference Include="Onion.Maui.GoogleMaps" Version="6.1.0" />
	<PackageReference Include="Oscore.Maui.Android.InAppUpdates" Version="1.2.0" />
	<PackageReference Include="Plugin.LocalNotification" Version="11.1.4" />
	<PackageReference Include="Roslynator.Analyzers" Version="4.12.10">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.30" />
	<PackageReference Update="Microsoft.Maui.Controls.Compatibility" Version="8.0.100" />
	<PackageReference Include="CommunityToolkit.Maui" Version="10.0.0" />
	<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="5.0.0" />
	<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
	<PackageReference Include="EzPasswordValidator" Version="2.1.0" />
	<PackageReference Include="GeoTimeZone" Version="5.3.0" />
	<PackageReference Include="LocalizationResourceManager.Maui" Version="1.2.1" />
	<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.1" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	<PackageReference Include="Oscore.Maui.Biometric" Version="2.2.1" />
	<PackageReference Include="Plugin.StoreReview" Version="7.0.0-beta" />
	<PackageReference Include="Prism.DryIoc.Maui" Version="9.0.537" />
	<PackageReference Include="Sharpnado.Tabs.Maui" Version="3.2.1" />
	<PackageReference Include="YoutubeExplode" Version="6.5.1" />
	<PackageReference Include="ZXing.Net.Maui.Controls" Version="0.4.0" />
</ItemGroup>

<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
	<PackageReference Include="Xamarin.AndroidX.Collection">
		<Version>1.4.5.1</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.AndroidX.Collection.Ktx">
		<Version>1.4.5.1</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.AndroidX.Fragment.Ktx">
		<Version>1.8.5.1</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.AndroidX.Lifecycle.Common">
		<Version>2.8.7.1</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core">
		<Version>2.8.7.1</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime">
		<Version>2.8.7.1</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.Firebase.Analytics">
		<Version>122.1.2.1</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.Firebase.Core">
		<Version>121.1.1.12</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.Firebase.Crashlytics">
		<Version>119.3.0</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.Firebase.Messaging">
		<Version>124.1.0</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.GooglePlayServices.Auth.Api.Phone">
		<Version>118.1.0.3</Version>
	</PackageReference>
	<PackageReference Include=" Xamarin.AndroidX.Lifecycle.LiveData.Core">
		<Version>2.8.7.1</Version>
	</PackageReference>
</ItemGroup>

<Target Name="LinkWithSwift" DependsOnTargets="_ParseBundlerArguments;_DetectSdkLocations" BeforeTargets="_LinkNativeExecutable">
	<PropertyGroup>
		<_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('iossimulator-'))">iphonesimulator</_SwiftPlatform>
		<_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('ios-'))">iphoneos</_SwiftPlatform>
	</PropertyGroup>
	<ItemGroup>
		<_CustomLinkFlags Include="-L" />
		<_CustomLinkFlags Include="/usr/lib/swift" />
		<_CustomLinkFlags Include="-L" />
		<_CustomLinkFlags Include="$(_SdkDevPath)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(_SwiftPlatform)" />
		<_CustomLinkFlags Include="-Wl,-rpath" />
		<_CustomLinkFlags Include="-Wl,/usr/lib/swift" />
	</ItemGroup>
</Target>

<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows'))">
	<XamarinBuildDownloadUser7ZipPath>C:\Program Files\7-Zip\7z.exe</XamarinBuildDownloadUser7ZipPath>
</PropertyGroup>
```

**Comment by LeoJHarris** [comment]
@AdamEssenmacher a few items omitted that I figure were not worth including, let me know if you need anymore information though.

**Comment by AdamEssenmacher** [comment]
Thank you. I don't see anything that should be causing problems.

Can you try 11.4.0 and 11.4.0.1 and report back?

Also, check your XamarinBuildDownload cache to make sure analytics was unpacked correctly to `FAnlytcs-11.4.0`

**Comment by LeoJHarris** [comment]
@AdamEssenmacher will try again today but struggled with this issue as I have previously.

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\.nuget\packages\adame.firebase.ios.installations\11.4.0\lib\net6.0-ios16.1\Firebase.Installations.resources\FirebaseInstallations.xcframework\ios-arm64_x86_64-simulator\FirebaseInstallations.framework\FirebaseInstallations_Privacy.bundle\PrivacyInfo.xcprivacy'.
```

**Comment by AdamEssenmacher** [comment]
> Could not find a part of the path

This is almost always the Windows long-path issue.

If you can build on mac, then the problem is in your Windows/Visual Studio configuration.

**Comment by LeoJHarris** [comment]
@AdamEssenmacher from memory updating/adding NuGets from package manager console seemed to work fine

> Can you try 11.4.0 and 11.4.0.1 and report back?

Was this for a particular set of packages? The package AdamE.Firebase.iOS.Core jumps those versions to 11.4.2

**Comment by AdamEssenmacher** [comment]
In general, all Firebase packages you import should be on the same major/minor version + latest patch.

**Comment by AdamEssenmacher** [comment]
> from memory updating/adding NuGets from package manager console seemed to work fine, I have LongPathsEnabled.

Try the debugging steps outlined in the project readme, or just build on Mac. You are on Windows and getting a 'DirectoryNotFoundException' for a path that is 262 characters long.

**Comment by bhavanesh2001** [comment]
@LeoJHarris The device your'e trying to build for, Is it a simulator or real device?

**Comment by LeoJHarris** [comment]
@bhavanesh2001 it is a real device.

**Comment by bhavanesh2001** [comment]
@LeoJHarris  Can you add this to you csproj and check?
```xml
<PropertyGroup>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
</PropertyGroup>
```

**Comment by LeoJHarris** [comment]
@AdamEssenmacher using the latest version of this package?

**Comment by bhavanesh2001** [comment]
@LeoJHarris Yes. Hoping it will fix the original error.

**Comment by LeoJHarris** [comment]
@LeoJHarris Still getting the same problem with latest NuGet and `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>`

**Comment by LeoJHarris** [comment]
> If you can build on mac, then the problem is in your Windows/Visual Studio configuration.

I only have my windows machine setup for development

**Comment by LeoJHarris** [comment]
> Also, check your XamarinBuildDownload cache to make sure analytics was unpacked correctly to `FAnlytcs-11.4.0`

Also saw this in the build:

![Image](https://github.com/user-attachments/assets/e9372fcd-181e-4312-b309-2bd9176536b8)

**Comment by LeoJHarris** [comment]
@AdamEssenmacher checked and seems to exist

![Image](https://github.com/user-attachments/assets/9fbb80b4-d969-44d8-a708-151c964c1ef3)

**Comment by LeoJHarris** [comment]
I'm not sure if this is reason for concern or not.

**Comment by AdamEssenmacher** [comment]
That's the long path issue. You can try following the instructions for a possible workaround in the readme.

**Comment by LeoJHarris** [comment]
@AdamEssenmacher Ill see what I can do on this a bit later as clearing the cache sometimes gets me stuck on the unpacking again for XamarinBuildDownload cache as this gets deleted from the work around, I manually add the file `GAppM-x.x.0.unpacked` and this seems to resolve the issue, not sure why this happens but seems like this gets me a little stuck.

**Comment by LeoJHarris** [comment]
@AdamEssenmacher I've become a little tied up on some other issues to resolve so parking this for the time being as it can be a little time consuming clearing the cache and then getting all the packages working.

**Comment by chrmeehansr** [comment]
@LeoJHarris - Would you be so kind as to share the information regarding the GAppM-x.x.0.unpacked solution / workaround? First, I'm happy to continue to guinea pig, test, contribute any way I can being somewhat of a new'ish developer, but 25yrs in the industry. By the way, thank you to Adam, Tobias and all for your work on this

I'm facing what looks to be the same issue. I followed everything in the readme. I was able to build on android, iOS physical and emulator, publish to stores, etc..) then came back to work on cross mobile push notifications for my solution with firebase and re-enabled all my iOS code, and hit with this again. Incrementally removed dependencies, tried versions from 10.24, iteratively all the way to 11.6. Updated/Downgraded Plugin.Firebase, tried what feels like every combination of build properties for debug, etc.. and can't seem to figure it out. Every time I test with changing dependencies & versions, I delete bin/obj (off root, c:\b & c:\o), clean and dotnet restore all packages I relocated to c:\n, clear xamarinbuildcache, build from command line before debug in VS. Added long path reg key/value. I am hit with clang++ exit code 1, error....   Thanks so much for any help in advance! -C

I also saw references to GoogleAppMeasurements not being found in the build output. 

I checked the file path of XamarinBuildsDownload cache and it looks as though the directory is present and populated...

C:\Users\xxxxxxxxx\AppData\Local\XamarinBuildDownloadCache\FAnlytcs-11.4.0

Undefined symbols for architecture arm64:
  "_APMAnalyticsConfiguration", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[10](FIRAnalytics.o)
  "_APMAppMeasurementOriginFirebase", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[10](FIRAnalytics.o)
  "_APMConsentSettings3P", referenced from:
      +[FIRAnalytics setConsent:] in FirebaseAnalytics[10](FIRAnalytics.o)
  "_APMFormattedEventName", referenced from:
      +[FIRAnalytics logEventWithOrigin:name:parameters:] in FirebaseAnalytics[10](FIRAnalytics.o)
  "_APMFormattedUserPropertyName", referenced from:
      +[FIRAnalytics setUserPropertyString:forName:] in FirebaseAnalytics[10](FIRAnalytics.o)
  "_APMIsAnalyticsCollectionDeactivated", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[10](FIRAnalytics.o)
  "_APMIsAnalyticsCollectionEnabled", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[10](FIRAnalytics.o)
  "_APMMonitorLogTagOptionKey", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[10](FIRAnalytics.o)
  "_APMUserDataFieldEmailAddress", referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithEmailAddress:] in FirebaseAnalytics[10](FIRAnalytics.o)
  "_APMUserDataFieldHashedEmailAddress", referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithHashedEmailAddress:] in FirebaseAnalytics[10](FIRAnalytics.o)
  "_APMUserDataFieldHashedPhoneNumber", referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithHashedPhoneNumber:] in FirebaseAnalytics[10](FIRAnalytics.o)
  "_APMUserDataFieldPhoneNumber", referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithPhoneNumber:] in FirebaseAnalytics[10](FIRAnalytics.o)

**Comment by AdamEssenmacher** [comment]
Hey @chrmeehansr,

`clang++ exit code 1` is a generic error—it just means the compiler failed, but doesn’t tell us why. The issue you’re facing may or may not be related to what OP initially reported, though the errors in your build log do look similar.

A key part of your error log is:

`Undefined symbols for architecture arm64`

This means clang (the C compiler) encountered references to symbols it couldn’t find—like `APMAnalyticsConfiguration`—and the missing symbols were referenced in functions like `+[FIRAnalytics startWithConfiguration:options:]`.

Why can't clang find these symbols? Here are some possible reasons:

- The required code isn’t downloaded.
- clang isn’t looking in the right place.
- The code is present but inaccessible.
- The code is corrupted.
- Duplicate definitions are causing conflicts.
- The wrong version of a dependency is being used.

To debug, let’s first narrow down where the problem originates:

- Is it an issue with the binding packages (i.e., this project)?
- Is it something in your project’s configuration?
- Is it related to your build environment?

Since Windows + Visual Studio has known flakiness with iOS builds via a linked Mac, I suggest first trying a direct build on a Mac. If it works, then we’ve isolated the problem to your Windows/VS build setup. Let me know what you find!

**Comment by chrmeehansr** [comment]
@AdamEssenmacher - Thank you. While I continue, thought I'd share this or can move/share it elsewhere to not confuse the thread if that makes sense? As it relates to some of the iOS build properties such as LLVM, SymbolStrip, etc.. As I still learn and dig that's something I'm still somewhat uncomfortable with and have tried many variations, so forgive my ignorance there if something is obviously way wrong. Last attempt I copied what was working in release to debug to try that but it could be all wrong now. Lastly, a bunch of other dependencies listed need to be cleaned up and removed but figured I'd share the list. 

Thanks again for the help. The only mac I have access to for this setup, believe it or not has an intermittent display issue and I got it all setup (again, was able to build and publish out to testFlight), via a remote shell and using the voice over accessibility features to navigate the OS with the keyboard. Crazyness but waiting on a new mac build host / monitor to get passed that. 



<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
  <_ExportSymbolsExplicitly>false</_ExportSymbolsExplicitly>
</PropertyGroup>

<Target Name="LinkWithSwift" DependsOnTargets="_ParseBundlerArguments;_DetectSdkLocations" BeforeTargets="_LinkNativeExecutable">
  <PropertyGroup>
    <_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('iossimulator-'))">iphonesimulator</_SwiftPlatform>
    <_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('ios-'))">iphoneos</_SwiftPlatform>
  </PropertyGroup>
  <ItemGroup>
    <_CustomLinkFlags Include="-L" />
    <_CustomLinkFlags Include="/usr/lib/swift" />
    <_CustomLinkFlags Include="-L" />
    <_CustomLinkFlags Include="$(_SdkDevPath)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(_SwiftPlatform)" />
    <_CustomLinkFlags Include="-Wl,-rpath" />
    <_CustomLinkFlags Include="-Wl,/usr/lib/swift" />
  </ItemGroup>
</Target>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
  <CodesignKey>Removed</CodesignKey>
  <CodesignProvision>Removed</CodesignProvision>
  <ProvisioningType>automatic</ProvisioningType>
  <MtouchDebug>True</MtouchDebug>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
  <ApplicationDisplayVersion>3.0.0</ApplicationDisplayVersion>
  <ApplicationVersion>3</ApplicationVersion>
  <ApplicationTitle>title</ApplicationTitle>
  <ApplicationId>com.companyname.title</ApplicationId>
  <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
  <MtouchLink>SdkOnly</MtouchLink>
  
  <MtouchUseLlvm>False</MtouchUseLlvm>
  
  <EnableSGenConc>True</EnableSGenConc>
  
  <NoSymbolStrip>True</NoSymbolStrip>
  <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
  <EmbedOnDemandResources>True</EmbedOnDemandResources>
  <SuppressTrimAnalysisWarnings>True</SuppressTrimAnalysisWarnings>
  
  <EnableTrimAnalyzer>False</EnableTrimAnalyzer>
  
  <MtouchExtraArgs>--aot=verbose</MtouchExtraArgs>
  <MtouchExtraArgs>--aot-options=limit-llvm-stack=400MB</MtouchExtraArgs>
  <MtouchExtraArgs>--aot=threads=1</MtouchExtraArgs>
  <MtouchInterpreter>True</MtouchInterpreter>
</PropertyGroup>

<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios'">
  <ApplicationDisplayVersion>3.0.0</ApplicationDisplayVersion>
  <ApplicationVersion>3</ApplicationVersion>
  <ApplicationTitle>title</ApplicationTitle>
  <ApplicationId>com.companyname.title</ApplicationId>
  <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
  <CodesignKey>iOS Distribution: Removed</CodesignKey>
  <CodesignProvision>Distribution</CodesignProvision>
  <ArchiveOnBuild>True</ArchiveOnBuild>
  <MtouchLink>SdkOnly</MtouchLink>
  
  <MtouchUseLlvm>False</MtouchUseLlvm>
  
  <EnableSGenConc>True</EnableSGenConc>
  
  <NoSymbolStrip>True</NoSymbolStrip>
  <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
  <EmbedOnDemandResources>True</EmbedOnDemandResources>
  <SuppressTrimAnalysisWarnings>True</SuppressTrimAnalysisWarnings>
  
  <EnableTrimAnalyzer>False</EnableTrimAnalyzer>
  
  <MtouchExtraArgs>--aot=verbose</MtouchExtraArgs>
  <MtouchExtraArgs>--aot-options=limit-llvm-stack=400MB</MtouchExtraArgs>
  <MtouchExtraArgs>--aot=threads=1</MtouchExtraArgs>
  <MtouchInterpreter>True</MtouchInterpreter>
</PropertyGroup>



<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
  <_ExportSymbolsExplicitly>false</_ExportSymbolsExplicitly>
</PropertyGroup>

<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
  <PackageReference Include="Plugin.Firebase" Version="3.1.3" />
  <PackageReference Include="Plugin.Firebase.Auth" Version="3.1.1" />
  <PackageReference Include="Plugin.Firebase.CloudMessaging" Version="3.1.2" />
  <PackageReference Include="Plugin.Firebase.Core" Version="3.1.1" />
  <PackageReference Include="AdamE.Firebase.iOS.Analytics" Version="11.6.0" />
  <PackageReference Include="AdamE.Firebase.iOS.Core" Version="11.6.0" />
  <PackageReference Include="AdamE.Firebase.iOS.Crashlytics" Version="11.6.0" />
  <PackageReference Include="AdamE.Firebase.iOS.Installations" Version="11.6.0" />
</ItemGroup>

<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
  <GoogleServicesJson Include="google-services.json" />
</ItemGroup>
<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
  <BundleResource Include="GoogleService-Info.plist" />
</ItemGroup>

<ItemGroup>
  <PackageReference Include="AppoMobi.Maui.DrawnUi" Version="1.2.3.8" />
  <PackageReference Include="CommunityToolkit.Maui" Version="10.0.0" />
  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  <PackageReference Include="DevExpress.Maui.CollectionView" Version="24.2.3" />
  <PackageReference Include="DevExpress.Maui.Controls" Version="24.2.3" />
  <PackageReference Include="DevExpress.Maui.Core" Version="24.2.3" />
  <PackageReference Include="DevExpress.Maui.DataGrid" Version="24.2.3" />
  <PackageReference Include="DevExpress.Maui.Editors" Version="24.2.3" />
  <PackageReference Include="EJL.MauiHybridWebView" Version="1.0.0-preview6" />
  <PackageReference Include="FirebaseAdmin" Version="3.0.0" />
  <PackageReference Include="Mapsui.ArcGIS" Version="4.1.7" />
  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.0" />
  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
  <PackageReference Include="Microsoft.Identity.Client" Version="4.66.2" />
  <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.66.2" />
  <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.3.0" />
  <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.21" />
  <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.21" />
  <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
  <PackageReference Include="Microsoft.Maui.Controls.Maps" Version="9.0.21" />
  <PackageReference Include="Microsoft.Maui.Essentials" Version="9.0.21" />
  <PackageReference Include="Microsoft.Maui.Graphics" Version="9.0.21" />
  <PackageReference Include="Microsoft.Maui.Maps" Version="9.0.21" />
  <PackageReference Include="Microsoft.SemanticKernel" Version="1.32.0" />
  <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.32.0" />
  <PackageReference Include="Onion.Maui.GoogleMaps" Version="6.1.0" />
  <PackageReference Include="OpenAI" Version="2.1.0" />
  <PackageReference Include="Plugin.AdMob" Version="1.1.0" />
  <PackageReference Include="RestSharp" Version="112.1.0" />
  <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
  <PackageReference Include="stream-chat-net" Version="2.6.0" />
  <PackageReference Include="Syncfusion.Licensing" Version="28.1.37" />
  <PackageReference Include="Syncfusion.Maui.Buttons" Version="28.1.37" />
  <PackageReference Include="Syncfusion.Maui.Calendar" Version="28.1.37" />
  <PackageReference Include="Syncfusion.Maui.Cards" Version="28.1.37" />
  <PackageReference Include="Syncfusion.Maui.Carousel" Version="28.1.37" />
  <PackageReference Include="Syncfusion.Maui.Core" Version="28.1.37" />
  <PackageReference Include="Syncfusion.Maui.Inputs" Version="28.1.37" />
  <PackageReference Include="Syncfusion.Maui.ListView" Version="28.1.37" />
  <PackageReference Include="Syncfusion.Maui.Maps" Version="28.1.37" />
  <PackageReference Include="Syncfusion.Maui.Rotator" Version="28.1.37" />
  <PackageReference Include="Syncfusion.Maui.Toolkit" Version="1.0.3" />
  <PackageReference Include="System.ClientModel" Version="1.2.1" />
  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.1.0" />
  <PackageReference Include="Xamarin.Build.Download" Version="0.11.4" />
  
</ItemGroup>

**Comment by AdamEssenmacher** [comment]
Try removing Plugin.Admob. That has a transient dependency on Xamarin.Firebase.iOS.Core, which could lead to:

> - Duplicate definitions are causing conflicts.
> - The wrong version of a dependency is being used.

Also, it is almost definitely a bad idea to have `FirebaseAdmin` in a client application. That's probably unrelated to your current build issue, but I thought I'd call it out for you.

**Comment by AdamEssenmacher** [comment]
@chrmeehansr did you get it figured out? I've seen a handful of other problems very similar to this, and the problem tends to be a bad XamarinBuildDownload cache on WIndows (due to the long path issue). Following the workaround instructions in the project readme seems to work for most.

**Comment by LeoJHarris** [comment]
This seems to be resolved using latest NuGets 11.10.0 so will close this issue now.
